version: "3.7"
services:
  app:
      # Ключевое слово "build" позволяет задать
      # путь к файлу Dockerfile, который нужно использовать для создания образа,
    build:
#
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: lrs
    container_name: lrs-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - lrs

  db:
    image: mysql:8.0.30
    container_name: lrs-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: lrs_db
      DB_USERNAME: root
      MYSQL_ROOT_PASSWORD: mynewpassword
      MYSQL_PASSWORD: mynewpassword
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    restart: unless-stopped
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - lrs
    ports:
      - "33061:3306"

  nginx:
    image: nginx:alpine
    container_name: lrs-nginx
    restart: unless-stopped
    ports:
      - 8009:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - lrs

networks:
  lrs:
    driver: bridge

